export const CONTACT_INFO = {
  phoneMTN: "+256 770 775268",
  phoneAirtel: "+256 751 527730",
  phoneMTNRaw: "+256770775268",
  phoneAirtelRaw: "+256751527730",
  phonePrimary: "+256 770 775268",
  phoneSecondary: "+256 751 527730",
  email: "medrisemedicalcentre@gmail.com",
  address: "Lwadda A, Matugga, Gombe Division, Wakiso District, Uganda",
  whatsapp: "https://wa.me/256751527730",
  website: "https://sites.google.com/view/medrise-medical-centre/home",
};

export const DEPARTMENTS = [
  {
    id: "general-consultation",
    name: "General Consultation",
    description: "Diagnosis and treatment of common illnesses and health conditions for patients of all ages.",
    icon: "ClipboardList",
    color: "lime",
  },
  {
    id: "opd",
    name: "Out Patient Department (OPD)",
    description: "Routine check-ups and outpatient diagnosis for walk-in patients without the need for overnight admission.",
    icon: "Stethoscope",
    color: "blue",
  },
  {
    id: "obs-gynae",
    name: "Obstetrics and Gynaecology",
    description: "Comprehensive maternal healthcare — antenatal and postnatal care, safe deliveries, family planning and gynaecological services.",
    icon: "Heart",
    color: "pink",
  },
  {
    id: "surgery",
    name: "Surgery",
    description: "Minor and major surgical procedures performed by experienced surgeons in a safe, sterile, fully equipped theatre.",
    icon: "Scissors",
    color: "red",
  },
  {
    id: "internal-medicine",
    name: "Internal Medicine",
    description: "Specialised diagnosis and management of complex conditions affecting internal organs including the heart, lungs and kidneys.",
    icon: "Activity",
    color: "green",
  },
  {
    id: "paediatrics",
    name: "Paediatrics",
    description: "Dedicated child healthcare from newborns through adolescence — vaccinations, growth monitoring and treatment of childhood illnesses.",
    icon: "Baby",
    color: "yellow",
  },
  {
    id: "imaging",
    name: "Imaging",
    description: "Modern diagnostic imaging including X-Ray, Ultrasound, CT Scan and Echocardiography for accurate clinical investigations.",
    icon: "ScanLine",
    color: "purple",
  },
  {
    id: "laboratory",
    name: "Laboratory",
    description: "On-site clinical laboratory offering a full range of tests — blood counts, malaria, HIV, liver and kidney function, and more.",
    icon: "FlaskConical",
    color: "teal",
  },
  {
    id: "pharmacy",
    name: "Pharmacy",
    description: "A well-stocked in-house pharmacy dispensing quality, affordable medicines and providing expert medication counselling.",
    icon: "Pill",
    color: "orange",
  },
  {
    id: "dental",
    name: "Dental Department",
    description: "Preventive and restorative dental care — cleanings, fillings, extractions and oral health education for the whole family.",
    icon: "Smile",
    color: "cyan",
  },
  {
    id: "ent",
    name: "ENT",
    description: "Expert management of Ear, Nose and Throat conditions including hearing loss, sinusitis, tonsillitis and throat infections.",
    icon: "Mic2",
    color: "indigo",
  },
];
